/*
    BASE DE DATOS PARA UNA INMOBILIARIA
*/

-- TABLA CON LOS DATOS BÁSICOS DE LA EMPRESA
CREATE TABLE COMPANY (
    NIF_COMPANY NUMBER PRIMARY KEY,
    NAME VARCHAR2(20),
    ADDRESS VARCHAR2(50),
    START_DATE DATE,
    EMAIL VARCHAR2(30)
);

-- DATOS DE LAS SUCURSALES DE LA EMPRESA
CREATE TABLE BRANCH_OFFICE (
    ID_BOFFICE NUMBER PRIMARY KEY,
    ADDRESS_BO VARCHAR2(50),
    START_BO_DATE DATE,
    PHONE_NUM VARCHAR2(15),
    ID_MANAGER NUMBER
);

-- DATOS DE LOS DEPARTAMENTOS DE LA EMPRESA
CREATE TABLE DEPTO(
    ID_DEPTO NUMBER PRIMARY KEY,
    NAME_DEPTO VARCHAR2(30)
);

-- DATOS SOBRE LOS PUESTOS DE TRABAJO
CREATE TABLE JOB(
    ID_JOB NUMBER PRIMARY KEY,
    NAME_JOB VARCHAR2(40),
    ID_DEPTO NUMBER
);

-- DATOS DE LOS EMPLEADOS DE LA EMPRESA
CREATE TABLE EMPLOYEES(
    ID_EMPLOYEE NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(10),
    LAST_NAME VARCHAR2(10),
    NIF_EMP VARCHAR2(20),
    ADDRESS_EMP VARCHAR2(50),
    BIRTH_DATE DATE,
    SDATE DATE,
    PHONE VARCHAR2(15),
    EMAIL VARCHAR2(30),
    ID_JOB NUMBER,--
    ID_DEPTO NUMBER,--
    ID_BOFFICE NUMBER,--
    SALARY NUMBER,
    WORKING_DAY VARCHAR2(30)
);

-- DATOS DE LOS CLIENTES DE LA EMPRESA
CREATE TABLE CUSTOMER(
    ID_CUST NUMBER PRIMARY KEY,
    NAME_CUST VARCHAR2(20),
    NIF_CUST VARCHAR2(20),
    ADDRESS_CUST VARCHAR2(30),
    PHONE_CUST VARCHAR2(15),
    EMAIL_CUST VARCHAR2(30)
);

-- DATOS DE LOS PROVEEDORES DE LA EMPRESA
CREATE TABLE SUPPLIERS(
    ID_SUP NUMBER PRIMARY KEY,
    NAME_SUP VARCHAR2(20),
    NIF_SUP VARCHAR2(20),
    ADDRESS_SUP VARCHAR2(50),
    PHONE_SUP VARCHAR2(20),
    EMAIL_SUP VARCHAR2(20)
);

-- DATOS DE LOS INMUEBLES O PROPIEDADES DE LOS CUALES DISPONE LA INMOBILIARIA PARA VENDER
CREATE TABLE PROPERTYS (
    ID_PROPERTY NUMBER PRIMARY KEY,
    NIF_PROPERTY VARCHAR2(20),
    ADDRESS_PROP VARCHAR2(50),
    GEOGRAPHICAL_COORDS VARCHAR2(30),
    BUILDING_DATE DATE,
    PUBLICATION_DATE_SALE DATE,
    PROPERTY_TYPE VARCHAR2(20),
    ID_SUP NUMBER,
    PRICE NUMBER
);

-- DATOS SOBRE LOS POSIBLES ESTADOS DE LA EMPRESA
CREATE TABLE STATUS_PROPERTY (
    ID_STATUS NUMBER PRIMARY KEY,
    STATUS VARCHAR2(30),
);

-- DATOS PARA EL CONTROL DE LA INFORMACIÓN SOBRE CADA INMUEBLE
CREATE TABLE FACT_PROPERTY (
    ID_FACTPROP NUMBER PRIMARY KEY,
    ID_PROPERTY NUMBER,
    ID_CUST NUMBER,
    ID_SUP NUMBER,
    ID_EMPLOYEE NUMBER,
    ID_STATUS NUMBER,
    FACT_DATE DATE
);


/*
    DECLARACIONES DE LLAVES FORANIAS PARA LAS TABLAS
*/
ALTER TABLE BRANCH_OFFICE
ADD FOREIGN KEY (ID_MANAGER)
REFERENCES EMPLOYEES(ID_EMPLOYEE);

ALTER TABLE JOB
ADD FOREIGN KEY (ID_DEPTO)
REFERENCES DEPTO(ID_DEPTO);

ALTER TABLE EMPLOYEES
ADD FOREIGN KEY (ID_JOB)
REFERENCES JOB(ID_JOB);

ALTER TABLE EMPLOYEES
ADD FOREIGN KEY (ID_DEPTO)
REFERENCES DEPTO(ID_DEPTO);

ALTER TABLE EMPLOYEES
ADD FOREIGN KEY (ID_BOFFICE)
REFERENCES BRANCH_OFFICE(ID_BOFFICE);

ALTER TABLE PROPERTYS
ADD FOREIGN KEY (ID_SUP)
REFERENCES SUPPLIERS(ID_SUP);

ALTER TABLE FACT_PROPERTY
ADD FOREIGN KEY (ID_PROPERTY)
REFERENCES PROPERTYS(ID_PROPERTY);

ALTER TABLE FACT_PROPERTY
ADD FOREIGN KEY (ID_CUST)
REFERENCES CUSTOMER(ID_CUST);

ALTER TABLE FACT_PROPERTY
ADD FOREIGN KEY (ID_SUP)
REFERENCES SUPPLIERS(ID_SUP);

ALTER TABLE FACT_PROPERTY
ADD FOREIGN KEY (ID_EMPLOYEE)
REFERENCES EMPLOYEES(ID_EMPLOYEE);

ALTER TABLE FACT_PROPERTY
ADD FOREIGN KEY (ID_STATUS)
REFERENCES STATUS_PROPERTY(ID_STATUS);
