/*
    BASE DE DATOS PARA EL DW DE UNA BASE DE DATOS PARA UNA INMOBILIARIA (Proyecto -BDDII)
    @author: its_anaehm
    @date: 03/03/2021
    @version: 0.
*/

-- TABLA DE DIMENSION PROPIEDADES
CREATE TABLE D_PROPIEDADES (
    ID_PROPERTY INT PRIMARY KEY,
    NIF_PROPERTY VARCHAR(20),
    PROPERTY_TYPE VARCHAR(20)
);

-- TABLA DE DIMENSION PROVEEDORES
CREATE TABLE D_PROVEEDORES (
    ID_SUP INT PRIMARY KEY,
    NAME_SUP VARCHAR(20),
    NIF_SUP VARCHAR(20)
);

-- TABLA DE DIMENSION EMPLEADOS
CREATE TABLE D_EMPLEADOS (
    ID_EMPLOYEE INT PRIMARY KEY,
    NAME VARCHAR(20)
);

-- TABLA DE DIMENSION CLIENTES
CREATE TABLE D_CLIENTES (
    ID_CUST INT PRIMARY KEY,
    NAME_CUST VARCHAR(20),
    NIF_CUST VARCHAR(20)
);

-- TABLA DE DIMENSION TIEMPO
CREATE TABLE D_TIEMPO (
    ID_TIEMPO DATE PRIMARY KEY,
    ANO INT,
    MES INT,
    DIA INT,
    TRIMESTRE INT,
    SEMESTRE INT,
    DIADESEMANA VARCHAR(20)
);

-- TABLA DE HECHOS DE VENTAS
CREATE TABLE H_VENTAS (
    ID_VENTAS INT IDENTITY(1,1) PRIMARY KEY,
    ID_PROPERTY INT,
    ID_SUP INT,
    ID_EMPLOYEE INT,
    ID_CUST INT,
    ID_TIEMPO DATE,
    PRECIO INT
);

ALTER TABLE H_VENTAS
ADD FOREIGN KEY (ID_PROPERTY)
REFERENCES D_PROPIEDADES(ID_PROPERTY);

ALTER TABLE H_VENTAS
ADD FOREIGN KEY (ID_SUP)
REFERENCES D_PROVEEDORES(ID_SUP);

ALTER TABLE H_VENTAS
ADD FOREIGN KEY (ID_EMPLOYEE)
REFERENCES D_EMPLEADOS(ID_EMPLOYEE);

ALTER TABLE H_VENTAS
ADD FOREIGN KEY (ID_CUST)
REFERENCES D_CLIENTES(ID_CUST);

ALTER TABLE H_VENTAS
ADD FOREIGN KEY (ID_TIEMPO)
REFERENCES D_TIEMPO(ID_TIEMPO);